module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    LOGIN_FAIL: "로그인 실패",
    LOGIN_SUCCESS: "로그인 성공",
    SIGNIN_FAIL: "회원가입 실패",
    SIGNIN_SUCCESS: "회원가입 성공",
    NOT_FIND_USER: "회원을 찾을 수 없음",
    ALREADY_ID: "ID중복",
    ABLE_ID: "사용가능한 ID",
    ALREADY_NICKNAME: "닉네임 중복",
    ABLE_NICKNAME: "사용가능한 닉네임",
    UNAUTHORIZED: "권한이 없는 유저입니다.",
    DB_ERROR : "서버 연동 실패.",
    INTERNAL_SERVER_ERROR : "서버 연동 오류",
    BOARD_REGIST_ALL_SUCCESS : "게시물 전체 조회 성공",
    BOARD_REGIST_ONE_SUCCESS : "게시물 하나 조회 성공",
    NEW_BOARD_SUCCESS : "게시물 등록 성공",
    UPDATE_BOARD_SUCCESS : "게시물 수정 성공",
    DELETE_BOARD_SUCCESS : "게시물 삭제 성공",
    MYPAGE_GET_SUCCESS : "마이 페이지 조회 성공",
    MYPAGE_UPDATE_SUCCESS : "마이 페이지 업데이트 성공",
    NEW_ITEM_REGIST_SUCCESS : "새로운 아이템 등록 성공",
    PAGING_SHOP_SUCCESS : "샵 페이징 로딩 성공",
    SHOP_ITEM_REGIST_SUCCESS : "샵 아이템 조회 성공",
    NEW_TRANSACTION_SUCCESS : "새로운 트랜잭션 생성 성공",
    GET_MY_TRANSACTION_SUCCESS : "나의 트랜잭션 가져오기 성공",
    NEW_COMMENT_SUCCESS : "새로운 댓글 생성 성공",
    DELETE_COMMENT_SUCCESS : "댓글 삭제 성공",
    GET_COMMENT_SUCCESS : "댓글 조회 성공",
    AUTHORIZATION_SUCCESS : "토큰 인증 성공",
    RE_AUTHORIZATION_SUCCESS : "토큰 만료, 재발급 성공"
};
